# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Location provider and night light
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = sleep 1 && gammastep

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move windows based on matches (e.g. pip)
exec-once = caelestia resizer -d

# Start shell
exec-once = caelestia shell -d

# Audio
exec-once = easyeffects --hide-window --service-mode
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk


exec-once=xrdb -merge ~/.Xresources
exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace
exec-once=fcitx5-remote -r
exec-once =  /usr/lib/kdeconnectd &
exec-once = obsidian  --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
exec-once = systemctl --user start hyprpolkitagent
exec-once = keepassxc --keyfile ~/data/kdbx/keyring.key ~/data/kdbx/local-keyring.kdbx
#exec-once = secret-tool lookup name xrpasswd | keepassxc --pw-stdin --keyfile /home/xuanran/.ssh/id_rsa ~/xrpasswd.kdbx
